/**
 * Foodie API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Offer } from './offer';
import { Transaction } from './transaction';

export interface Order {
  readonly id?: number;
  readonly user_id?: string;
  readonly offer_id?: string;
  readonly order_date?: string;
  products: Array<Transaction>;
  delivery_date: string;
  readonly total?: number;
  offer?: Offer;
}
